services:
  nginx:
    build: ./nginx
    ports:
      - "8080:80"
    depends_on:
      - service_1
      - service_2

  service_1:
    build: ./service_1
    expose:
      - "8001"

  service_2:
    build: ./service_2
    expose:
      - "8002"
